### ISSUE TITLE
[Feature Request]Attach files to tasks

### ISSUE THREAD

**Issue by hg2581** [dmfs/opentasks#557] opened 2017-12-07 11:39 UTC
Thunderbird task manager allows files to be attached to tasks, this is a useful feature that should be added to OpenTasks.

**Comment by dmfs** [comment] 2017-12-07 21:15
Duplicate of #57. It's on our list for some time. It's one of the next things we'll work on when recurrence is finally done.

**Closed by dmfs** 2017-12-07 21:15 UTC
Labels: duplicate
