### ISSUE TITLE
[feature] Possibility of handling repeating tasks?

### ISSUE THREAD

**Issue by rexxmagnus** [dmfs/opentasks#434] opened 2017-10-04 14:19 UTC
I see that Thunderbird has the option of having a task automatically repeat on a given period. Is there potential for this to be implemented, so that a task gets marked as incomplete when the repeat period starts?

**Comment by BlueIce** [comment] 2017-10-04 19:26
Possible duplicate of #26, #233 and #367.

**Comment by dmfs** [comment] 2017-10-04 21:46
Right. FTR, we're working on test utilities to be able to test handling of recurring tasks in the provider: #418, #422

**Comment by dmfs** [comment] 2017-10-18 11:26
This is now tracked under #462

**Closed by dmfs** 2017-10-18 11:26 UTC
