### ISSUE TITLE
No task details in portrait mode

### ISSUE THREAD

**Issue by Lykos153** [dmfs/opentasks#271] opened 2016-09-20 14:05 UTC
OpenTasks no longer shows the task details (title, due date etc), just a blank header. Sometimes I can see them for half a second after selecting the task, but then they dissappear. In landscape mode, everything works as expected. (See images below)

This behaviour is reproducable on the following devices. Maybe it's a CM issue, but I don't know.

OnePlus One with Cyanogen OS 13.1.2 (Android 6.0.1)
Galaxy Tab S2 with CyanogenMod 13

![portrait_header](https://cloud.githubusercontent.com/assets/6453662/18673112/eefbedae-7f20-11e6-9be3-cc2fd38431d1.jpg)
![landscape_header](https://cloud.githubusercontent.com/assets/6453662/18673246/76a0b370-7f21-11e6-9978-a421e9cc4be8.jpg)

**Comment by robertauer** [comment] 2016-10-03 08:17
I have the exact same problem.
My Device:
Samsung Galaxy S4 (GT-I9505) with Cyanogenmod 13.0 (20160820 SNAPSHOT) (->Android 6.0.1)

**Comment by dmfs** [comment] 2016-10-09 16:08
duplicate of #241.

**Closed by dmfs** 2016-10-09 16:08 UTC
Labels: duplicate
