### ISSUE TITLE
Disable notifications for disabled lists

### ISSUE THREAD

**Issue by gonebiking** [dmfs/opentasks#110] opened 2014-09-28 08:32 UTC
I have two calendars, my personal calendar and one shared from my wife. She puts her tasks in her calendar, I put mine in my calendar. We both display in the app Tasks only our own tasks.
But we still get the task notifications of the not displayed task list. Feels like a bug to me.

**Comment by Flachzange** [comment] 2015-07-17 16:26
Same for us, we really appreciate this feature and are looking forward to seeing it in the next version. Thanks for your work.

**Comment by dmfs** [comment] 2015-12-10 11:07
This appears to be a duplicate of #97 or at least the proposed solution is the same. Closing this in favor of #97

**Closed by dmfs** 2015-12-10 11:07 UTC
Labels: duplicate, enhancement
