### ISSUE TITLE
Start of week in calendar on Android 7

### ISSUE THREAD

**Issue by hg2581** [dmfs/opentasks#882] opened 2019-11-14 15:19 UTC
On my tablet running Android 7, the calendar picker does not allow me to change the start of the week. Despite using the US defaults, I want my weeks to start with Monday, not Sunday. In the Business Calendar app this can be changed and I would like to suggest that this be possible in OpenTasks as well.

**Comment by dmfs** [comment] 2019-11-14 15:26
Closing this as duplicate of #753 and #376

**Closed by dmfs** 2019-11-14 15:26 UTC
