### ISSUE TITLE
OpenTasks loses tasks when force stopped

### ISSUE THREAD

**Issue by zingmars** [dmfs/opentasks#730] opened 2018-11-24 10:41 UTC
On OnePlus 6T with Android 9.0 using DAVDroid to sync to a Nextcloud backend.

After a while (no idea how much time it takes though. Definitely hours) the widget will stop showing current tasks. Pressing on the widget will open the OpenTasks app with all the tasks present there, but they will not show up on the widget. The tasks will be there after I recreate the widget but will disappear after a while.

**Comment by zingmars** [comment] 2018-11-28 17:34
I can recreate this by killing (force stop) the Tasks app. Pressing the refresh button eventually repopulates the task list (forcing davdroid sync also works).

**Comment by dmfs** [comment] 2018-12-03 04:40
This is most likely related to/caused by #728 / #596. I've started to work on the workaround #728 but the real solution would be that DavDroid allows OpenTasks to see the accounts.

**Comment by marier-nico** [comment] 2018-12-17 12:49
I'm glad to hear a workaround is being worked on. I just wanted to a add that I'm encountering the same issue on my OnePlus 3T, running Android 8.

**Comment by HNJAMeindersma** [comment] 2019-01-08 22:06
I have the exact same problem, in combination with #732. Will try <s>2.2.1</s> 2.2.2 in a bit to see if it's fixed according to #728.

**Comment by dmfs** [comment] 2019-01-11 21:10
This should be fixed in the latest DAVx5 release as well as OpenTasks 1.1.16. Please reopen if this is still an issue with the latest releases.

**Closed by dmfs** 2019-01-11 21:10 UTC
