### ISSUE TITLE
Crash App on widget creating

### ISSUE THREAD

**Issue by Vasya-Kl** [dmfs/opentasks#152] opened 2015-07-31 15:09 UTC
Good day.

Version below 1.1.6 don't see any CalDAV Task Accounts, only Local.
But widget work correctly.

Version 1.1.6 work fine with CalDAV Task Accounts.
And Crash on widget creating.
Crash after selecting from two possible.
Widget don't creating.

Help please.

--
Android 2.3.7.
And i like it.

**Comment by Vasya-Kl** [comment] 2015-08-04 08:58
I/dalvikvm(11610): Could not find method android.appwidget.AppWidgetManager.notifyAppWidgetViewDataChanged, referenced from method org.dmfs.tasks.homescreen.TaskListWidgetProviderLarge.onReceive
I/dalvikvm(11610): Could not find method android.appwidget.AppWidgetManager.notifyAppWidgetViewDataChanged, referenced from method org.dmfs.tasks.homescreen.TaskListWidgetProvider.onReceive
W/dalvikvm(11610): Unable to resolve superclass of Lorg/dmfs/tasks/homescreen/TaskListWidgetUpdaterService; (1490)
W/dalvikvm(11610): Link of class 'Lorg/dmfs/tasks/homescreen/TaskListWidgetUpdaterService;' failed
E/dalvikvm(11610): Could not find class 'org.dmfs.tasks.homescreen.TaskListWidgetUpdaterService', referenced from method org.dmfs.tasks.homescreen.TaskListWidgetProvider.onUpdate
W/dalvikvm(11610): VFY: unable to resolve const-class 1976 (Lorg/dmfs/tasks/homescreen/TaskListWidgetUpdaterService;) in Lorg/dmfs/tasks/homescreen/TaskListWidgetProvider;
D/dalvikvm(11610): VFY: dead code 0x017f-0211 in Lorg/dmfs/tasks/homescreen/TaskListWidgetProvider;.onUpdate (Landroid/content/Context;Landroid/appwidget/AppWidgetManager;[I)V
I/ActivityManager( 6928): Starting: Intent { act=android.appwidget.action.APPWIDGET_CONFIGURE cmp=org.dmfs.tasks/.homescreen.TaskListWidgetSettingsActivity (has extras) } from pid 7038
E/ActivityThread(11610):        at org.dmfs.tasks.homescreen.TaskListSelectionFragment.onCreateView(TaskListSelectionFragment.java:92)
E/AndroidRuntime(11610): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.dmfs.tasks/org.dmfs.tasks.homescreen.TaskListWidgetSettingsActivity}: android.view.InflateException: Binary XML file line #41: Error inflating class <unknown>
E/AndroidRuntime(11610):        at org.dmfs.tasks.homescreen.TaskListSelectionFragment.onCreateView(TaskListSelectionFragment.java:92)
W/ActivityManager( 6928):   Force finishing activity org.dmfs.tasks/.homescreen.TaskListWidgetSettingsActivity
W/ActivityManager( 6928): Activity pause timeout for HistoryRecord{40a46b60 org.dmfs.tasks/.homescreen.TaskListWidgetSettingsActivity}
I/ActivityManager( 6928): Process org.dmfs.tasks (pid 11610) has died.
I/WindowManager( 6928): WIN DEATH: Window{40bca3c8 org.dmfs.tasks/org.dmfs.tasks.TaskListActivity paused=false}W/ActivityManager( 6928): Activity destroy timeout for HistoryRecord{40a46b60 org.dmfs.tasks/.homescreen.TaskListWidgetSettingsActivity}

**Comment by Vasya-Kl** [comment] 2015-08-04 08:58
Help please.

**Comment by dmfs** [comment] 2015-08-05 21:25
What kind of device do you use? We'll have a look into this.

**Comment by donguijote** [comment] 2015-11-25 17:39
I have same problem, widget crashes.
I'm using an HTC Hero with Android 2.3.7 (with custom root "Cronos Ginger X 0.1.0")

**Comment by dmfs** [comment] 2015-11-25 21:11
The bug is caused by a reference to a non-existing color in the support library. I've added a workaround so I can add widgets now. There still seems to be another issue with the widget on Android 2.x though. Right now it's not updated when I add or update tasks.

**Comment by dmfs** [comment] 2016-02-10 12:46
This has been fixed in 1.1.8.

**Closed by dmfs** 2016-02-10 12:46 UTC
Labels: bug
