### ISSUE TITLE
Title not shown when viewing task

### ISSUE THREAD

**Issue by PanderMusubi** [dmfs/opentasks#241] opened 2016-06-01 04:37 UTC
The title is not shown when viewing task, see attachment. This was reported for Android 6.0.1 (but was also there on Android 5) with Cyanogen OS 13.0. Please fix this. Contact me if I can help testing.

![screenshot_20160502-225824](https://cloud.githubusercontent.com/assets/198964/15698272/27f144d4-27c3-11e6-97ab-2763203bb98b.png)

**Comment by untitaker** [comment] 2016-06-17 14:38
I'm experiencing the same issue.

**Comment by dmfs** [comment] 2016-06-17 18:22
Does that happen for all tasks?

**Comment by untitaker** [comment] 2016-06-17 18:29
Yes. Also the summary shortly flashes up when opening the activity for the first time.

On 17 June 2016 20:22:38 CEST, Marten Gajda <notifications@github.com> wrote:
>Does that happen for all tasks?
>
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/dmfs/opentasks/issues/241#issuecomment-226844230

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dmfs** [comment] 2016-06-18 19:31
@untitaker are you on Cyanogen OS as well?
I can't reproduce this on stock Android 5 or 6.

**Comment by PanderMusubi** [comment] 2016-06-18 20:45
For me it is still there on Android 6.0.1 Cyanogen OS 13.1

**Comment by untitaker** [comment] 2016-06-19 06:39
Yes I'm on Cyanogenmod nightly.

On 18 June 2016 22:45:11 CEST, Pander <notifications@github.com> wrote:
>For me it is still there on Android 6.0.1 Cyanogen OS 13.1
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/dmfs/opentasks/issues/241#issuecomment-226963937

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by keassol** [comment] 2016-06-25 03:44
FYI, I just noticed that for me this only happens if the task has no list items.  If there are items the title does show.  No items, no title.

**Comment by untitaker** [comment] 2016-06-25 06:34
For me the title appears if I add task items, but after closing the app through "recent apps" it doesn't reappear.

On 25 June 2016 06:44:28 EEST, keassol <notifications@github.com> wrote:
>FYI, I just noticed that for me this only happens if the task has no
>list items.  If there are items the title does show.  No items, no
>title.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/dmfs/opentasks/issues/241#issuecomment-228507855

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by PanderMusubi** [comment] 2016-06-27 09:34
With mine, independent of closing through "recent apps", the title appear very shortly and then disappears. It is still there, because if there is a url I can tap on it ant it opens, but it is not visible.

**Comment by Dark-Fenix** [comment] 2016-07-25 07:34
Hi,

I have the same issue (Cyanogen 13.0, Android 6.0.1). I confirm that adding items in the list sometimes make the title appears, sometimes not. And I also confirm that the fields are still there, just hidden : I can press the "+1 day" button on the bottom left.
I tried a full reset of my phone and a clean reinstall, the bug is still here.

**Comment by korelstar** [comment] 2016-08-03 11:12
I'm using Cyanogen OS 13.0 (Android 6.0.1) too, but I doesn't have this bug. Very strange thing.

**Comment by yringot** [comment] 2016-08-26 08:38
Same here but only in portrait mode. In landscape mode the title appears again.

**Comment by yringot** [comment] 2016-08-26 08:39
Cyanogen mod 13 (android 6.0.1)

**Comment by dmfs** [comment] 2016-08-31 21:52
The upcoming release should fix this.

**Closed by dmfs** 2016-08-31 21:52 UTC
Labels: bug

**Comment by untitaker** [comment] 2016-09-28 12:23
Could you cut a new release for this? This issue is a dealbreaker for me...
