### ISSUE TITLE
Notification for closed task appear

### ISSUE THREAD

**Issue by htbecker** [dmfs/opentasks#806] opened 2019-06-09 18:27 UTC
Since a few weeks I receive notifcations for a closed tasks. I can only remove this notification by deleting the task. The notifications even appear after a restart of the phone.
I can observe the same behavior on a second phone.
The phone is a Huawei (BLA-L29) and runs on Android 9. OpenTasks run in version 1.1.18

**Comment by dmfs** [comment] 2019-06-09 20:39
This one is probably related to #805

**Comment by dmfs** [comment] 2019-06-09 20:41
Possibly a duplicate of #800

**Comment by daladim** [comment] 2019-06-27 06:52
Will you soon push the fix to Google Play Store? Or should we rather build it from source? (in that case, must I uninstall the Google play version first?)

Thanks for your work!

**Comment by amilopowers** [comment] 2019-07-03 12:08
I have the same problem with two phones: Nokia 6.1 and 7.1 both running Android 9.

**Comment by dmfs** [comment] 2019-07-04 21:37
This will definitely go into the next release. I'm just waiting for feedback on the recurring task code from testing. I hope to start the staged roll-out next week.

**Comment by dmfs** [comment] 2019-07-30 14:09
This should be fixed in 1.1.20

**Closed by dmfs** 2019-07-30 14:09 UTC
Labels: bug
