### ISSUE TITLE
Feature Request: Change calendar of Task / Move Task between calendar

### ISSUE THREAD

**Issue by dynobo** [dmfs/opentasks#222] opened 2016-03-07 06:42 UTC
Hi,
I really love this android app, but I really miss the possibility to move a task from one calendar to another. So it would be really cool, if I could change the calendar of a task after it's been created.
Thanks!

**Comment by wweich** [comment] 2016-03-07 08:08
duplicate of #18, #46, #181 and #198.

**Comment by dmfs** [comment] 2016-03-07 13:09
This feature has been implemented and released in 1.1.8.
You can change the list of a task in the editor by hitting the list field on top.

**Closed by dmfs** 2016-03-07 13:09 UTC
Labels: duplicate

**Comment by PanderMusubi** [comment] 2016-03-08 14:37
I also could not find this without checking here first. I think people expect that this is a function you would get by longpressing on a list of tasks and finding the option: move to another task list (calendar)

**Comment by dmfs** [comment] 2016-03-08 15:17
We've considered to implement this by drag'n'drop on the list view and we certainly will implement it like that eventually (after we've refactored the list views).
We're trying to move away from long presses and context menu as much as possible.
