### ISSUE TITLE
CalDAV tasks without start date but no due date are not shown in widget

### ISSUE THREAD

**Issue by mcassaniti** [dmfs/opentasks#196] opened 2016-02-02 01:54 UTC
Hi,
First of all thanks for your app. I used to use Mirakel with an old version of DAVdroid and it's nice to move to something much more reliable.

I've found that if I don't set a due date on my tasks they also don't show on the widget. Is this by design, and if so can an option be added to modify the display settings for the widget? Considering the requests to modify the way tasks are displayed in the widget, I believe adding options to adjust the widget display is worthwhile.

I'm also looking forward to the addition of alarm editing within the widget.

**Comment by wweich** [comment] 2016-02-02 10:55
If I add a task without due date (just entered a title) it is immediately displayed in the widget.
Where did you create the task? Inside the OpenTasks app? I still have the issue, that adding tasks outside the app (e.g. without owncloud) the widget does not refresh after sync, but only ass soon a a task is created/edited/deleted within the app.

**Comment by mcassaniti** [comment] 2016-02-02 22:49
I appreciate your quick response. I did the following with an existing task that had both a due date and a start date:
- Removed due date via the app which caused the widget to not display the task
- Removed the start date via the app which caused the widget to display the task again
- Added the due date only back in via the app which caused the widget to display the task (and its due date)

It seems that a start date only without a due date causes the widget to not display the task. Please note that all my changes were done within the app, but the list is backed by CalDAV. I've updated the issue title accordingly.

**Comment by dmfs** [comment] 2016-02-02 23:02
Please note that the widget currently only shows tasks that have started already, which means they have either no start date or a start date in the past. The idea is to not bother the user with tasks that are not relevant yet. However we've plans to add a mechanism to customize the tasks shown by the widget.
I'm closing this, since it's (currently) intended behavior. It will be changed, though.

**Closed by dmfs** 2016-02-02 23:02 UTC

**Comment by mcassaniti** [comment] 2016-02-02 23:03
Thanks for the explanation and your quick response.
