### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by dilyanpalauzov** [dmfs/opentasks#714] opened 2018-10-23 14:09 UTC
Add support for attachments, that can eventually be mapped to [draft-ietf-calext-caldav-attachments](https://tools.ietf.org/html/draft-ietf-calext-caldav-attachments-03)

**Comment by dmfs** [comment] 2018-10-24 20:44
I consider this a duplicate of #57.

**Closed by dmfs** 2018-10-24 20:44 UTC
