### ISSUE TITLE
Unnecessary notifications after a (re-)start of the phone

### ISSUE THREAD

**Issue by bachmi** [dmfs/opentasks#805] opened 2019-06-09 15:56 UTC
Since some weeks I face the following issue when starting my Android phone. After a (re-)start I will be notified in the notification bar about a significant number of tasks with no clear reason why.
Due dates have not been reached yet for them. I never set start dates. I am running about altogether 60 open tasks and about 20 to 30 tasks will appear in such cases. I am not able to determine which are shown here (due dates vary from in a few days to in a some weeks).
Expected and existing behavior of the App (as I have seen in the past) was no such unnecessary notifications after a (re-)start of the phone.

I am using DAVx5 to sync my CALDAV calendars.

OpenTasks Version: 1.1.18
Phone : Google Pixel 3
Android Version: 9

**Comment by dmfs** [comment] 2019-06-09 20:41
This could be a duplicate of #800. Do they reappear on reboot when you pin and un-pin the task once?

**Comment by bachmi** [comment] 2019-06-10 08:05
If have checked this now with several tasks. When pin and un-pin them before a reboot, such tasks will not reappear.

**Comment by dmfs** [comment] 2019-06-10 09:38
Ok, in this case I'll close this as a duplicate of #800.

**Closed by dmfs** 2019-06-10 09:38 UTC
Labels: bug
