### ISSUE TITLE
Pinned task triggers the notification LED

### ISSUE THREAD

**Issue by mase76** [dmfs/opentasks#399] opened 2017-08-02 06:40 UTC
Hi!
When I pinned a task, the LED notifies me all the time.
Notification via LED should be for task alarms only.

**Comment by dmfs** [comment] 2017-08-02 08:33
Which device and Android version? I can't reproduce this on my device.

**Comment by mase76** [comment] 2017-08-02 10:14
I have a Sony Xperia X with Omnirom. Android is 7.1.2.
Notification is only when screen is off, not all the time.

**Comment by lemonboston** [comment] 2017-08-03 16:37
I can't really try to replicate this, the emulator's screen can't be turned off and also that LED on it is probably for illustration purposes.

Controlling the LED for notification would be done with [.setLight()](https://developer.android.com/reference/android/support/v4/app/NotificationCompat.Builder.html#setLights(int,%20int,%20int)) but we don't use that in the codebase.

I tried to search for the issue for Sony Xperia, didn't find anything meaningful, searching for Omnirom and LED blinking does have some results but none of them clearly about this.

@mase76 Does this happen only with OpenTasks notifications? So if you have a notification from another app which you let on and turn off the screen, the LED doesn't blinks?

The other thing we can look into whether the notification priority can affect this, I see that we set HIGH at some places. To check whether anything has changed in Nougat for example regarding this.

**Comment by lemonboston** [comment] 2017-08-03 16:54
We also set the default lights flag here:
```
        if (withSound)
        {
            builder.setDefaults(Notification.DEFAULT_ALL);
        }
        else
        {
            builder.setDefaults(Notification.DEFAULT_LIGHTS);
        }
```
But if this worked so far then I suppose it should probably work the same way for Nougat as well.

**Comment by mase76** [comment] 2017-08-03 16:59
Other apps with notifications, for example K9mail don't notify by LED. But in the K9mail options I can enable LED notification. Openkeychain, Orbot, or any other app also do not notify by LED, when it is not wanted.

**Comment by lemonboston** [comment] 2017-08-09 16:41
@mase76 And when you enable LED notification in K9mail and have a notification from that when screen turned off, is the LED blinking the same way as for OpentTasks pinned tasks? By the way, is it blinking or continuous light?

**Comment by mase76** [comment] 2017-08-09 17:42
The LED in K9 blinks  the same way when the screen is off. The only difference is the colour. K9 blinks blue, OT blinks white.

**Comment by lemonboston** [comment] 2017-08-10 16:04
I can actually reproduce this with my device as well (Nexus 5, Android 6), I was under the wrong assumption that it is Android 7 related.
So when "Pulse notification light" is enabled in phone settings and I pin a task and turn off the screen, I see the LED blinking. I've also found the code which sets this behavior up that pin notifications has the lights by default.

I am working on a settings screen where notification sound/vibration/blinking can be turned on/off, it will be fixed as part of that.

**Comment by lemonboston** [comment] 2017-08-10 17:10
https://github.com/dmfs/opentasks/pull/403 suppose to fix this.

**Closed** 2017-10-09 20:16 UTC
Labels: bug
