### ISSUE TITLE
Sync of local changes triggers DavX syncloop

### ISSUE THREAD

**Issue by jason076** [dmfs/opentasks#740] opened 2019-01-18 09:21 UTC
I am using DavX to sync my tasks with my Synology NAS. If i do a local change in Opentask DavX beginns to sync about every 5 seconds and the phone beginns to vibrate in the same interval. If I uninstall Opentask the syncloop is stopped, thus I think its a bug in Opentask and not in DavX.

There seem to be many people experiencing the same problem, if you look at the reviews in GooglePlay.

I have recognized that the App OneDrive gets stuck in a syncloop too. At least the notifications implies that, because they appear and disappear approximately every second. Can there be a connection to the bug in Opentask?

**Comment by dmfs** [comment] 2019-01-18 12:44
I wouldn't conclude that OpenTasks is the culprit just because the sync loop stops when it's uninstalled. How could there be a sync loop if the task database is not available? If sync in general is interrupted the sync loop is also interrupted.

I'll check whether made any changed since 1.1.13 which could cause this. However, there may well be changes in DavX which cause this issue.

Can you provide any logs?

FWIW: I can't reproduce the issue with our own sync app.

Any connection to an issue in OneDrive would be pure coincidence, unless it's actually caused by Android.

**Comment by dmfs** [comment] 2019-01-18 14:01
This is the diff since the previous release: https://github.com/dmfs/opentasks/compare/1.1.13...1.1.16#diff-a2d9992674dba3695927f124d604a7b4

The fragment points to `TaskProvider.java`. So far I've not been able to see any change which might cause a sync loop. This could only be the case when a change made by a sync adapter triggers another sync but I can't find any evidence for this, especially since this line (which decides whether a provider change triggers a sync or not) remained unchanged: https://github.com/dmfs/opentasks/blob/master/opentasks-provider/src/main/java/org/dmfs/provider/tasks/SQLiteContentProvider.java#L317
Note that the `callerIsSyncAdapter` flag is determined per request.

Other possible reasons for a sync loop are:
* a sync adapter makes a change without identifying itself as a sync adapter
* a system setting is changed which causes Android to trigger a sync

**Comment by dmfs** [comment] 2019-01-18 19:54
> I have thought that the local task database is maintained by DavX and OpenTask just connects to the Database maintained by DavX.

No, it's the other way round. OpenTasks provides the database (via it's TaskProvider) and DavX acts as the sync adapter and syncs the server with this database. You can see that by the fact that OpenTasks can also be used standalone, without any sync (although that's not recommended because it doesn't support backups yet) or with other sync apps. It works just like the system calendar database.

The log looks more like a DavX or server issue. There are frequent TCP timeouts.
>```
>EXCEPTION java.io.InterruptedIOException: interrupted
	at okio.Timeout.throwIfReached(Timeout.java:146)
```
Not sure why they trigger another sync though. I think that's DavX specific. None of the errors indicate that OpenTasks is involved.

**Comment by jason076** [comment] 2019-01-19 13:18
Okay, many thanks for reviewing my log files!
If I find the cause of the problem, I will let you know!

**Comment by jason076** [comment] 2019-01-19 13:19
Okay, many thanks for reviewing my log files!
If I find the cause of the problem, I will let you know!

**Comment by Simounet** [comment] 2019-04-09 06:42
Hi,
I had the exact same issue when I tried to use opentasks 1.1.17 but rolled back to 1.1.13 and everything is working fine. I tried with 1.1.15 and same issue. I don't know if that helps.
@jason076 Did you manage to make it working?

**Comment by jason076** [comment] 2019-04-09 11:31
@Simounet I had no time to further investigate the issue, thus I am still experiencing the bug.

> I had the exact same issue when I tried to use opentasks 1.1.17 but rolled back to 1.1.13 and everything is working fine. I tried with 1.1.15 and same issue. I don't know if that helps.

I tried the rollback to 1.1.13 and it seems to work for me too. But that should not be the solution. I have installed 1.1.15 and my phone starts again vibrating a few times in a short amount of time, if I add or remove a task. I have examined the DavX debug log, but I can't find anything suspicious there.

**Comment by dmfs** [comment] 2019-04-09 20:14
Please check if this is still an issue in 1.1.18.

**Comment by Simounet** [comment] 2019-04-09 20:21
I can't see it on fdroid right now. I'll wait and let you know when it will be available.

**Comment by HNJAMeindersma** [comment] 2019-04-10 17:17
@Simounet https://github.com/dmfs/opentasks/blob/master/releases/opentasks-1.1.18.apk

**Comment by Simounet** [comment] 2019-04-10 17:47
I've got this issue:
```
Authority: org.dmfs.tasks

REMOTE RESOURCE:
https://domain.tld/remote.php/dav/calendars/User/default/123456-654c-44fd-8e04-da4654da6.ics

EXCEPTION:
at.bitfire.ical4android.InvalidCalendarException: Couldn't parse iCalendar object
	at at.bitfire.ical4android.Task$Companion.fromReader(Task.kt:69)
	at at.bitfire.davdroid.syncadapter.TasksSyncManager.processVTodo(TasksSyncManager.kt:140)
	at at.bitfire.davdroid.syncadapter.TasksSyncManager.access$processVTodo(TasksSyncManager.kt:44)
	at at.bitfire.davdroid.syncadapter.TasksSyncManager$downloadRemote$2$1$1.invoke(TasksSyncManager.kt:126)
	at at.bitfire.davdroid.syncadapter.TasksSyncManager$downloadRemote$2$1$1.invoke(TasksSyncManager.kt:44)
	at at.bitfire.davdroid.syncadapter.SyncManager.useRemote(SyncManager.kt:820)
	at at.bitfire.davdroid.syncadapter.TasksSyncManager$downloadRemote$2$1.invoke(TasksSyncManager.kt:113)
	at at.bitfire.davdroid.syncadapter.TasksSyncManager$downloadRemote$2$1.invoke(TasksSyncManager.kt:44)
	at at.bitfire.dav4jvm.Response$Companion.parse(Response.kt:211)
	at at.bitfire.dav4jvm.DavResource$processMultiStatus$2.invoke(DavResource.kt:465)
	at at.bitfire.dav4jvm.DavResource.processMultiStatus(DavResource.kt:484)
	at at.bitfire.dav4jvm.DavResource.processMultiStatus(DavResource.kt:435)
	at at.bitfire.dav4jvm.DavCalendar.multiget(DavCalendar.kt:151)
	at at.bitfire.davdroid.syncadapter.TasksSyncManager$downloadRemote$2.invoke(TasksSyncManager.kt:112)
	at at.bitfire.davdroid.syncadapter.TasksSyncManager$downloadRemote$2.invoke(TasksSyncManager.kt:44)
	at at.bitfire.davdroid.syncadapter.SyncManager.useRemote(SyncManager.kt:809)
	at at.bitfire.davdroid.syncadapter.SyncManager.useRemoteCollection(SyncManager.kt:830)
	at at.bitfire.davdroid.syncadapter.TasksSyncManager.downloadRemote(TasksSyncManager.kt:111)
	at at.bitfire.davdroid.syncadapter.SyncManager$syncRemote$1$1.run(SyncManager.kt:451)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:784)
Caused by: net.fortuna.ical4j.data.ParserException: Error at line 8:Attempt to invoke virtual method 'java.util.TimeZone java.util.Calendar.getTimeZone()' on a null object reference
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:158)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:198)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:178)
	at at.bitfire.ical4android.Task$Companion.fromReader(Task.kt:67)
	... 23 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.TimeZone java.util.Calendar.getTimeZone()' on a null object reference
	at java.text.DateFormat.getTimeZone(DateFormat.java:704)
	at net.fortuna.ical4j.model.DateTime.<init>(DateTime.java:236)
	at net.fortuna.ical4j.model.DateTime.<init>(DateTime.java:244)
	at net.fortuna.ical4j.model.property.UtcProperty.<init>(UtcProperty.java:67)
	at net.fortuna.ical4j.model.property.Created.<init>(Created.java:86)
	at net.fortuna.ical4j.model.property.Created$Factory.createProperty(Created.java:143)
	at net.fortuna.ical4j.model.PropertyFactoryImpl.createProperty(PropertyFactoryImpl.java:72)
	at net.fortuna.ical4j.data.CalendarBuilder$ContentHandlerImpl.startProperty(CalendarBuilder.java:326)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.parse(CalendarParserImpl.java:245)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.access$1100(CalendarParserImpl.java:229)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:210)
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.parse(CalendarParserImpl.java:422)
	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.access$900(CalendarParserImpl.java:406)
	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:208)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendar(CalendarParserImpl.java:115)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendarList(CalendarParserImpl.java:180)
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:149)
	... 26 more
```

**Comment by jason076** [comment] 2019-04-10 18:42
@dmfs

Version 1.1.18 seems to fix the issue for me!

**Comment by Simounet** [comment] 2019-04-10 19:37
Ok, it was more like a davdroid cache issue. It seems to be working right now. 🤞 
Thanks!

**Comment by dmfs** [comment] 2019-04-10 19:58
Great! I'm closing this again.

**Closed by dmfs** 2019-04-10 19:58 UTC
