### ISSUE TITLE
Widget goes blank after DAVx^5 sync

### ISSUE THREAD

**Issue by 05nelsonm** [dmfs/opentasks#732] opened 2019-01-02 11:54 UTC
Widget when placed on home screen will properly show tasks, but after a DAVx^5 sync occurs, it goes blank. Tasks are still there when I open the app though.

**Comment by 05nelsonm** [comment] 2019-01-02 17:48
Happens on phone restart, too.

**Comment by kleinarne** [comment] 2019-01-03 06:17
As explained [URL=https://github.com/dmfs/opentasks/issues/730#issuecomment-443587101]here[/URL] by @dmfs, 
this is most likely related to/caused by #728 / #596.

**Comment by dmfs** [comment] 2019-01-11 21:09
This should be fixed in the latest DAVx5 release as well as OpenTasks 1.1.16. Please reopen if this is still an issue with the latest releases.

**Closed by dmfs** 2019-01-11 21:09 UTC
