### ISSUE TITLE
Ghosts notifications/vibrations

### ISSUE THREAD

**Issue by HNJAMeindersma** [dmfs/opentasks#768] opened 2019-02-07 13:13 UTC
Since a day or 5 I keep getting ghost vibrations on my Android. After a search I was told to go to Notifications panel in the Android settings menu and look for the app which initiates this. And every time after a ghost vibration it tells me that my last notification (0 minutes ago) was from OpenTasks. Note: no notification is actually displayed, only a short double vibration. Any fix for this?

I'm on **OpenTasks 1.1.17** on **Android 9** (Nokia 7 Plus)

_Maybe in relation to #731?_

**Comment by dmfs** [comment] 2019-02-11 22:24
Yes, I think this is a duplicate of #731. I'm working on it.

**Comment by HNJAMeindersma** [comment] 2019-02-18 14:04
> Yes, I think this is a duplicate of #731. I'm working on it.

Great! Happen to have an ETA?

**Comment by dmfs** [comment] 2019-02-18 22:15
fixing the ghost notifications is the first step of the redesign.

**Comment by amo13** [comment] 2019-03-02 14:34
Noticed the same issue on my phone. Occurred with both Lineage 15.1 and Lineage 16.
A short glance at the logs reveal a repeating entry:
`03-01 01:48:07.679  1000  1596  1596 I NotificationService: Cannot find enqueued record for key: 0|org.dmfs.tasks|-10|null|10097`
Hope that helps somehow :)
Thank you for working on it!

**Comment by dmfs** [comment] 2019-04-08 19:20
This should be resolved with 1.1.18, currently in staged roll out on Google Play. Please reopen if this issue still exists in 1.1.18.

**Closed by dmfs** 2019-04-08 19:20 UTC

**Comment by danxensen** [comment] 2019-04-20 22:39
@dmfs F-droid still has version 1.1.17, do you know when it will be updated there? I prefer to install apps through F-droid when available.

**Comment by dmfs** [comment] 2019-04-21 22:42
sorry, I have no idea. Check out #550
