### ISSUE TITLE
Description of "Local"

### ISSUE THREAD

**Issue by Valdnet** [dmfs/opentasks#911] opened 2020-01-27 19:56 UTC
The description "Local" should be translated. If it takes the name from the android system it should be according to the language set.

![obraz](https://user-images.githubusercontent.com/47037905/73208789-57381c80-4147-11ea-9894-fa00ba43566b.png)

App:
Android 6
OpenTasks 1.2.3

**Comment by dmfs** [comment] 2020-01-27 20:01
Thank you. I'm closing this as a duplicate of #264

**Closed by dmfs** 2020-01-27 20:01 UTC
