### ISSUE TITLE
Keyboard is always set to lower case

### ISSUE THREAD

**Issue by fbruetting** [dmfs/opentasks#284] opened 2016-10-09 00:00 UTC
Somehow the keyboard is preset to use lower case every time for the first word. I've never seen this in Android before, please correct this behaviour! :)

**Comment by dmfs** [comment] 2016-10-09 09:12
Does that affect all fields? I guess that's caused by the input type of the EditText elements.

**Comment by fb87** [comment] 2016-10-09 11:19
Yes, this occurs on every text input field.

**Comment by lemonboston** [comment] 2016-10-10 16:15
I am not sure I understand the issue, because lower case is the default behavior for EditText's. We don't apply any special capitalizing as I see it.
Should we change that? If yes, to which one, capitalize each word or only start of sentence? ([InputType](https://developer.android.com/reference/android/text/InputType.html#TYPE_TEXT_FLAG_CAP_SENTENCES)) To all EditTexts in the app, or should we list them here first to select which one needs which kind of capitalization?
Thanks.

**Comment by fb87** [comment] 2016-10-10 17:57
Capitalizing the start of each input field text would be nice! Think this fits everywhere.

Gabor Keszthelyi <notifications@github.com> schrieb am 10.10.2016 18:15:

I am not sure I understand the issue, because lower case is the default behavior for EditText's. We don't apply any special capitalizing as I see it.
Should we change that? If yes, to which one, capitalize each word or only start of sentence? (InputType) To all EditTexts in the app, or should we list them here first to select which one needs which kind of capitalization?
Thanks.

**Comment by lemonboston** [comment] 2016-10-11 10:26
@dmfs Can you please confirm that we should set all input text fields in the app, listed below, to capitalize first letters, i.e. set `InputType` to [TYPE_TEXT_FLAG_CAP_SENTENCES](https://developer.android.com/reference/android/text/InputType.html#TYPE_TEXT_FLAG_CAP_SENTENCES):

Create/rename list dialog
Quick add task dialog
Edit/create task screen:
-Title
-Location
-Descritption
-Checklist items
(-URL - no change)

**Comment by dmfs** [comment] 2016-10-12 18:00
Yes, I think that totally makes sense in most languages. There may be languages in which it's not common to do that though. So we should keep this in mind. For now we change this for all languages.

**Comment by lemonboston** [comment] 2016-10-13 11:54
Ok, I created the pull request.

While we are at it, there are other texts (not input fields) in the app which seemed strange for me first when I saw them in the app that they are lowercase. Like the status, priorities, privacy:
_needs action, in process, done, cancelled, incomplete
none, low, medium, high, urgent
not specified, public, private, confidential_
Should we maybe capitalize them as well? I think that some people (I think mostly technical people) like to use and see lowercase everywhere, but I would assume that's not the majority. But I am not sure of course, and I am not even a real user, so this is really just a question.

**Comment by fb87** [comment] 2016-10-13 16:19
I'm a technical person (:p), but this just applies to source code, where (depending on the language and project) variables are started lowercase. This doesn't apply to the regular language, since grammar in all languages known to me, requires every sentence and headings to be started upper case. So I'd make them upper case, too.

**Comment by dmfs** [comment] 2016-10-13 17:36
well, but these words are not used in the context of a sentence or a headline.
Anyway, according to https://material.google.com/style/writing.html#writing-tone these should indeed be capitalized. Please raise a separate issue.

**Comment by fb87** [comment] 2016-10-13 17:56
What for?

**Comment by dmfs** [comment] 2016-10-13 18:22
Because changing all labels to uppercase is completely a different issue. This one is already fixed by the pull request. And will be closed when the PR is merged.
Also it's lower priority, because it doesn't really affect usability, but "merely" the appearance.
Since @lemonboston raised the issue he should file a separate ticket.

**Comment by fb87** [comment] 2016-10-13 18:26
I'd say this is included, as you can reference multiple commits with this bug, but ok.

**Comment by lemonboston** [comment] 2016-10-14 10:30
Separate issue raised for capitalizing those text: #290.

**Comment by fbruetting** [comment] 2017-03-16 20:08
With half a year passed by and commits done to the source, I wonder why this wasn't included in an update…?

**Closed** 2017-09-08 12:27 UTC
Labels: bug
